name: Release starter and migration packages on tag push

on:
  workflow_dispatch:
  push:
    tags: [ '*' ]

jobs:
  zip-and-release-packages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set release version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Prepare release folder
        run: |
          mkdir packages

      - name: Zip starter
        uses: montudor/action-zip@v1
        with:
          args: >
            zip -r packages/starter.zip . \
                \
                -x "*.git/*" \
                -x ".github/*" \
                -x "spotless/*" \
                -x "docs/*" \
                \
                -x "CODEOWNERS" \
                -x "LICENSE" \
                -x "README.md" \
                \
                -x "packages/" \
                -x "packages/starter.zip" \
                -x "packages/migration.zip"

      - name: Zip migration
        uses: montudor/action-zip@v1
        with:
          args: >
            zip -r packages/migration.zip . \
                \
                -x "*.git/*" \
                -x ".github/*" \
                -x "spotless/*" \
                -x "docs/*" \
                -x "src/*" \
                \
                -x "CODEOWNERS" \
                -x "LICENSE" \
                -x "README.md" \
                \
                -x "packages/" \
                -x "packages/starter.zip" \
                -x "packages/migration.zip"

      - name: Release tag
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ env.RELEASE_VERSION }}-packages"
          prerelease: false
          title: "${{ env.RELEASE_VERSION }} starter and migration packages"
          files: packages/*
